#! /bin/bash

# a script to compile whatever file I want

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

compile_tex()
{
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}

refresh_mupdf()
{
    killall -SIGHUP mupdf
}

compile()
{
    case "$file" in
        *\.c) make ;;
        *\.cc) make ;;
        *\.cpp) make ;;
        *\.h) make ;;
        *\.hpp) make ;;
        *\.rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla && refresh_mupdf ;;
        *\.Rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla && refresh_mupdf ;;
        *\.md) pandoc -V geometry:margin=1in -o "$base.pdf" "$file" && refresh_mupdf ;;
        *\.tex) compile_tex ;;
        *\.ts) tsc *.ts ;;
        *) exit ;;
    esac
}


# if we can't find the directory, get out
cd "$dir" || exit

compile
